---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: orangecloudfoundry/elpaaso-pipelines
    tag: 'base'

inputs:
- name: elpaaso-pipelines
- name: mattermost-integrator-github

outputs:
- name: release-info

run:
  path: elpaaso-pipelines/mattermost/tasks/check-version.sh
