---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/busyboxplus
    tag: 'curl'

inputs:
- name: elpaaso-pipelines
- name: mattermost-integrator-github

run:
  path: elpaaso-pipelines/mattermost/task/check-version.sh
