---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: orange-cloudfoundry/elpaaso-pipelines
    tag: 'cf'

inputs:
- name: elpaaso-pipelines
- name: mattermost-integrator-github

outputs:
- name: deployment

run:
  path: elpaaso-pipelines/mattermost/tasks/deploy.sh
