resource_types:
- name: travis
  type: docker-image
  source:
    repository: orangeopensource/travis-resource-image
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-url}}
  - name: mattermost-integrator-travis
    type: travis
    source:
      repository: cloudfoundry-community/mattermost-cf-integrator
      branch-regex: v.*
      github-token: {{github-token}}
  - name: 50m-during-midnight-hour
    type: time
    source:
      interval: 50m
      start: 12:00 AM -0700
      stop: 1:00 AM -0700
  - name: mattermost-integrator-github
    type: github-release
    source:
      user: cloudfoundry-community
      repository: mattermost-cf-integrator
      access_token: {{github-token}}
  - name: elpaaso-pipelines
    type: git
    source:
      uri: https://github.com/ArthurHlt/elpaaso-pipelines.git
      branch: master
  - name: deploy-mattermost
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
jobs:
  - name: mattermost-release
    plan:
      - get: 50m-during-midnight-hour
        trigger: true
      - get: mattermost-integrator-github
      - get: elpaaso-pipelines
      - task: release-new-version
        file: elpaaso-pipelines/mattermost/tasks/check-version.yml
        params:
          accepted_version: "[0-2]{1}\\.[0-9]{1,2}\\.[0-9]{1,2}"
          slack_url: {{slack-url}}
          slack_channel: {{slack-channel}}
          slack_username: Concourse
          slack_icon: "https://pbs.twimg.com/profile_images/714899641628753920/3C8UrVPf.jpg"
      - put: mattermost-integrator-github
        params:
          tag: release-info/tag_to_release
          name: release-info/name_of_release
          body: release-info/body
          tag_prefix: v
  - name: wait-travis-build
    plan:
      - get: mattermost-integrator-github
      - get: elpaaso-pipelines
      - get: mattermost-integrator-travis
        trigger: true
      - task: wait-build-from-travis
        file: elpaaso-pipelines/mattermost/tasks/check-travis.yml
  - name: deploy-to-cf
    plan:
      - get: elpaaso-pipelines
      - get: mattermost-integrator-github
      - get: mattermost-integrator-travis
        trigger: true
        passed: [wait-travis-build]
      - task: deploy
        file: elpaaso-pipelines/mattermost/tasks/deploy.yml
        params:
          app_name: {{app-name}}
          mattermost_config: {{mattermost-config}}
          cf_api: {{cf-api}}
          cf_username: {{cf-username}}
          cf_password: {{cf-password}}
          cf_organization: {{cf-org}}
          cf_space: {{cf-space}}
      - put: deploy-mattermost
        params:
          manifest: deployment/mattermost/manifest.yml
          path: deployment/mattermost/
          current_app_name: {{app-name}}
      - put: slack-alert
        params:
          text_file: deployment/tag
          icon_url: https://pbs.twimg.com/profile_images/714899641628753920/3C8UrVPf.jpg
          text: |
            @channel Hey, I have just deployed a new version of our mattermost, we are on the $TEXT_FILE_CONTENT.
          channel: "#town-square"
          username: Concourse