resource_types:
- name: travis
  type: docker-image
  source:
    repository: orangeopensource/travis-resource-image

resources:
  - name: mattermost-integrator-travis
    type: travis
    source:
      repository: cloudfoundry-community/mattermost-cf-integrator
      branch-regex: v.*
      github-token: {{github-token}}
  - name: 5m-during-midnight-hour
    type: time
    source:
      interval: 50m
      start: 12:00 AM -0700
      stop: 1:00 AM -0700
  - name: mattermost-integrator-github
    type: github-release
    source:
      user: cloudfoundry-community
      repository: mattermost-cf-integrator
      access_token: {{github-token}}
  - name: mattermost-elpaaso-git
    type: git
    source:
      uri: {{mattermost-elpaaso-url}}
      branch: master
  - name: elpaaso-pipelines
    type: git
    source:
      uri: https://github.com/ArthurHlt/elpaaso-pipelines.git
      branch: master
  - name: resource-deploy-web-app
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
jobs:
  - name: mattermost-release
    plan:
      #- get: 5m-during-midnight-hour
      #  trigger: true
      - get: mattermost-integrator-github
      - get: elpaaso-pipelines
      - task: release-new-version
        file: elpaaso-pipelines/mattermost/tasks/check-version.yml
        params:
          cf_api: {{cf-api}}
          cf_username: {{cf-username}}
          cf_password: {{cf-password}}
          cf_organization: {{cf-org}}
          cf_space: {{cf-space}}
      - put: mattermost-integrator-github
        params:
          tag: release-info/tag_to_release
          name: release-info/name_of_release
          body: release-info/body
          tag_prefix: v
  - name: wait-travis-build
    plan:
      - get: mattermost-integrator-travis
        trigger: true
        passed: [mattermost-release]
      - task: wait-build-from-travis
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          run:
            path: echo
            args: ["build finish!"]
